# Generated by Django 3.1.1 on 2020-09-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge_article',
            name='recruitment_time',
            field=models.IntegerField(default=5, verbose_name='время набора участников'),
            preserve_default=False,
        ),
    ]
