# Generated by Django 3.1.1 on 2020-09-19 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_challenge_article_recruitment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.picture_user_directory_path)),
                ('description', models.TextField(null=True, verbose_name='Описание к картинке')),
            ],
        ),
        migrations.AlterModelOptions(
            name='challenge_article',
            options={'verbose_name': 'Челлендж', 'verbose_name_plural': 'Челленджи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 21, 46, 21, 206283), verbose_name='дата начала'),
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=500, verbose_name='статус пользователя')),
                ('contacts', models.CharField(max_length=200, verbose_name='контакты пользователя')),
                ('avatar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge_to_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'creator'), ('participant', 'participant')], max_length=50)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.challenge_article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user_data')),
            ],
        ),
        migrations.AddField(
            model_name='challenge_article',
            name='avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
    ]
