# Generated by Django 3.1.1 on 2020-09-19 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200919_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 22, 24, 28, 462324), verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
    ]
