# Generated by Django 3.1.1 on 2020-09-19 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200919_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 0, 16, 15, 624207), verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='temp'),
        ),
    ]
