# Generated by Django 3.1.1 on 2020-09-21 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200920_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge_article',
            name='users',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.challenge_to_user'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='challenges',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.challenge_to_user'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='recruitment_time',
            field=models.IntegerField(verbose_name='время челледжа'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 24, 22, 430960), verbose_name='дата начала'),
        ),
    ]
