# Generated by Django 3.1.1 on 2020-09-21 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200921_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 25, 44, 242778), verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='users',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.challenge_to_user'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='challenges',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.challenge_to_user'),
        ),
    ]
