# Generated by Django 3.1.1 on 2020-09-22 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200921_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge_article',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='challenges',
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 12, 17, 22, 924401), verbose_name='дата начала'),
        ),
    ]
