# Generated by Django 3.1.1 on 2020-09-22 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200922_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.challenge_article'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 12, 23, 28, 242108), verbose_name='дата начала'),
        ),
    ]
