# Generated by Django 3.1.1 on 2020-11-08 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200922_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='recruitment_time',
            field=models.IntegerField(verbose_name='время челледжа (в днях)'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 15, 52, 55, 7075), verbose_name='дата начала'),
        ),
    ]
