# Generated by Django 3.1.1 on 2020-11-08 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 15, 53, 5, 572537), verbose_name='дата начала'),
        ),
    ]
