# Generated by Django 3.1.1 on 2020-11-26 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 18, 3, 11, 790659), verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=2500, verbose_name='Аватар'),
        ),
    ]
