# Generated by Django 3.1.1 on 2020-11-26 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201126_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=2500, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 18, 53, 19, 475980), verbose_name='дата начала'),
        ),
    ]
