# Generated by Django 3.1.1 on 2020-11-26 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201126_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_article',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=2500, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 20, 25, 53, 140934), verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=2500, null=True, verbose_name='Аватар'),
        ),
    ]
