# Generated by Django 3.1.1 on 2020-11-29 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201126_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge_article',
            name='participants',
            field=models.ManyToManyField(through='main.Challenge_to_User', to='main.User_data'),
        ),
        migrations.AlterField(
            model_name='challenge_article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 0, 12, 53, 908185), verbose_name='дата начала'),
        ),
    ]
